---
abstract: "Default Boilerplate for Joelle Maslak's Code"
author:
  - 'Joelle Maslak <jmaslak@antelope.net>'
build_requires:
  Test::More: '1.001014'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JTM-Boilerplate
provides:
  JCM::Boilerplate:
    file: lib/JCM/Boilerplate.pm
    version: '1.021'
  JTM::Boilerplate:
    file: lib/JTM/Boilerplate.pm
    version: '1.021'
requires:
  AnyEvent::Delay: '0.001'
  AnyEvent::Handle::UDP: '0.043'
  AnyEvent::Ping: '0.011'
  Bytes::Random::Secure: '0.29'
  CHI: '0.6'
  CLDR::Number: '0.19'
  Carp: '1.38'
  Crypt::SmbHash: '0.12'
  Cwd: '3.60'
  DBD::SQLite: '1.48'
  DBI: '1.634'
  Data::Dumper: '2.154'
  Data::Printer: '0.36'
  Data::Validate::IP: '0.26'
  DateTime: '1.21'
  DateTime::Format::DateParse: '0.05'
  Devel::Size: '0.80'
  Digest::SHA1: '2.13'
  Dist::Zilla: '5.042'
  Dist::Zilla::Plugin::Git: '2.036'
  Dist::Zilla::Plugin::GitHub: '0.42'
  Dist::Zilla::Plugin::MetaProvides::Package: '2.003001'
  Dist::Zilla::Plugin::OSPrereqs: '0.007'
  Dist::Zilla::Plugin::PodWeaver: '4.006'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0.161170'
  EV: '4.22'
  Email::Valid: '1.198'
  English: '1.09'
  File::Copy: '2.30'
  File::Flock::Tiny: '0.14'
  File::Slurp: '9999.19'
  File::Slurper: '0.008'
  FindBin: '1.51'
  IO::File: '1.16'
  IO::Pipe: '1.15'
  IO::Prompter: '0.004014'
  IO::Select: '1.22'
  Import::Into: '1.002005'
  Inline: '0.80'
  Inline::C: '0.78'
  Lingua::EN::Numbers: '2.03'
  List::Util: '1.42'
  Log::Log4perl: '1.47'
  MIME::Base64: '3.15'
  Mail::Sender: v0.8.23
  Math::Random::ISAAC::XS: '1.004'
  Mercury: '0.008'
  Mojolicious: '6.65'
  Moose: '2.1604'
  Moose::Util::TypeConstraints: '2.1604'
  MooseX::Clone: '0.06'
  MooseX::Singleton: '0.29'
  MooseX::StrictConstructor: '0.19'
  Net::DNS: '1.05'
  Net::LDAP: '0.65'
  Net::XMPP: '1.05'
  NetAddr::IP: '4.078'
  PAR::Packer: '1.030'
  POSIX: '1.53'
  Parallel::WorkUnit: '1.009'
  Perl6::Slurp: '0.051005'
  Privileges::Drop: '1.03'
  Proc::Daemon: '0.22'
  Readonly: '2.00'
  Regexp::Common: '2015121601'
  Smart::Comments: '1.06'
  Socket6: '0.26'
  Storable: '2.51'
  Sys::Hostname::FQDN: '0.11'
  Term::ANSIColor: '4.04'
  Term::ReadKey: v2.30.1
  Term::Tmux::Layout: '1.003'
  Test::Exception: '0.40'
  Test::Fork: '0.002'
  Test::More: '1.001014'
  Test::Strict: '0.36'
  Time::HiRes: '1.9739'
  Try::Tiny: '0.24'
  UNIVERSAL: '1.12'
  YAML::Syck: '1.29'
  autodie: '2.29'
  feature: '0'
  forks: '0.36'
  namespace::autoclean: '0.28'
  perl: v5.22.0
  re: '0'
  strict: '0'
  warnings: '0'
version: '1.021'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.73'
