---
abstract: "Default Boilerplate for Joel's Code"
author:
  - 'Joel Maslak <jmaslak@antelope.net>'
build_requires:
  Test::More: '1.001014'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.042, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JCM-Boilerplate
requires:
  Bytes::Random::Secure: '0.29'
  Carp: '1.38'
  Crypt::SmbHash: '0.12'
  Cwd: '3.60'
  Data::Dumper: '2.154'
  DateTime: '1.21'
  DateTime::Format::DateParse: '0.05'
  Digest::SHA1: '2.13'
  Email::Valid: '1.198'
  File::Copy: '2.30'
  File::Flock::Tiny: '0.14'
  File::Slurp: '9999.19'
  File::Slurper: '0.008'
  FindBin: '1.51'
  IO::Pipe: '1.15'
  IO::Prompter: '0.004014'
  IO::Select: '1.22'
  Import::Into: '1.002005'
  List::Util: '1.42'
  MIME::Base64: '3.15'
  Math::Random::ISAAC::XS: '1.004'
  Mojo::Base: '6.38'
  Moose: '2.1604'
  Moose::Util::TypeConstraints: '2.1604'
  MooseX::Clone: '0.06'
  MooseX::StrictConstructor: '0.19'
  Net::DNS: '1.04'
  Net::LDAP: '0.65'
  POSIX: '1.53'
  Proc::Daemon: '0.22'
  Smart::Comments: '1.06'
  Storable: '2.51'
  Term::ANSIColor: '4.04'
  Term::ReadKey: v2.30.1
  Test::Exception: '0.40'
  Test::More: '1.001014'
  Try::Tiny: '0.24'
  TryCatch: '1.003002'
  YAML::Syck: '1.29'
  autodie: '2.29'
  feature: '0'
  namespace::autoclean: '0.28'
  perl: v5.22.0
  warnings: '0'
version: '1.004'
