theme: dark
ignore-tags:
 - shopping
monitor:
  display-time: False
trello:
  tasks:
   "Goals":
     "Today": "theme"
   "Personal Tasks":
     "Today": "personal"
   "Work Tasks":
     "Today": "work"
